CREATE DATABASE TAREA7Y8;
USE TAREA7Y8;

CREATE TABLE VACUNA
(
ID INT NOT NULL IDENTITY,
MARCA VARCHAR(100) PRIMARY KEY
);

SELECT * FROM VACUNA;

CREATE TABLE PROVINCIA
(
ID INT NOT NULL IDENTITY,
NOMBRE VARCHAR(100) PRIMARY KEY
);

SELECT * FROM PROVINCIA;

CREATE TABLE PERSONA
(
ID INT NOT NULL PRIMARY KEY IDENTITY,
CEDULA VARCHAR(100),
NOMBRE VARCHAR(200),
TELEFONO VARCHAR(100),
FECHA_NACIMIENTO VARCHAR(100),
VACUNA VARCHAR(100) REFERENCES VACUNA(MARCA),
PROVINCIA VARCHAR(100) REFERENCES PROVINCIA(NOMBRE)
);

SELECT * FROM PERSONA;

